version: "3.4"

# IMPORTANT NOTE: Volume paths mounted on containers are relative to the
# directory that this file is in (`docker/`) and so probably need to start with
# `../` to refer to a directory in the main code checkout

volumes:
  postgres:
  redis:
  influxdb:
  rabbitmq:

networks:
  musicbrainzdocker_odyssey-net:
    external: true

services:

  lbdb:
    image: postgres:9.5.3
    volumes:
      - postgres:/var/lib/postgresql/data:z
    networks:
      - musicbrainzdocker_odyssey-net

  redis:
    image: redis:5.0.3
    volumes:
      - redis:/data:z
    networks:
      - musicbrainzdocker_odyssey-net

  influx:
    image: influxdb:1.2.4
    volumes:
      - influxdb:/var/lib/influxdb:z
    environment:
      INFLUXDB_REPORTING_DISABLED: 'true'
      INFLUXDB_META_LOGGING_ENABLED: 'false'
      INFLUXDB_DATA_QUERY_LOG_ENABLED: 'false'
      INFLUXDB_DATA_WAL_LOGGING_ENABLED: 'false'
      INFLUXDB_DATA_DATA_LOGGING_ENABLED: 'false'
      INFLUXDB_HTTP_LOG_ENABLED: 'true'
      INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED: 'false'
    networks:
      - musicbrainzdocker_odyssey-net

  rabbitmq:
    image: rabbitmq:3.6.5
    volumes:
      - rabbitmq:/var/lib/rabbitmq:z
    networks:
      - musicbrainzdocker_odyssey-net

  web:
    build:
      context: ..
      dockerfile: Dockerfile
      target: listenbrainz-dev
    command: python3 /code/listenbrainz/manage.py runserver -h 0.0.0.0 -p 80 -d
    image: web
    volumes:
      - ..:/code/listenbrainz:z
      - ../listenbrainz/webserver/static:/static
      - /home/robert/listenbrainz-server/annoy:/annoy
    ports:
      - "80:80"
    depends_on:
      - redis
      - lbdb
      - influx
      - rabbitmq
    networks:
      - musicbrainzdocker_odyssey-net

  static_builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.webpack
    command: npm run build:dev
    volumes:
      - ..:/code/listenbrainz:z
      - ../listenbrainz/webserver/static:/static:z
    networks:
      - musicbrainzdocker_odyssey-net

